CREATE OR REPLACE PROCEDURE CARGA_INCREMENTAL_CLIENTE
AS
TABLE_DOES_NOT_EXIST EXCEPTION;
PRAGMA EXCEPTION_INIT(TABLE_DOES_NOT_EXIST, -942);
CREA_TABLA_TEMP VARCHAR(2000);
BEGIN
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_CLIENTE';
    EXECUTE IMMEDIATE 'DROP TABLE TEMP_CLIENTE';
EXCEPTION
    WHEN TABLE_DOES_NOT_EXIST THEN NULL;
END; 
CREA_TABLA_TEMP := 'CREATE GLOBAL TEMPORARY TABLE TEMP_CLIENTE ON COMMIT PRESERVE ROWS AS SELECT * FROM(
  (SELECT DNI, CUENTA, NOMBRE, APELLIDO1, APELLIDO2, C_O.ID_PROV, DIR, C_L.FEC_AUDIT FROM DIM_CLIENTE C_L
    RIGHT OUTER JOIN (SELECT 
    C.DNI,
    C.CUENTA,
    C.NOMBRE,
    C.APELLIDO1,
    C.APELLIDO2,
    D.ID_PROV,
    C.DIR
    FROM CLIENTE C LEFT OUTER JOIN DIM_PROV D ON C.CIUDAD = UPPER(D.DES_NOM_PROV)) C_O
    ON (C_O.DNI = C_L.ID_DNI AND C_O.CUENTA = C_L.COD_CUENTA AND C_O.NOMBRE = C_L.DES_NOMBRE AND C_O.APELLIDO1 = C_L.DES_APE1 
      AND C_O.APELLIDO2 = C_L.DES_APE2 AND C_O.ID_PROV = C_L.ID_PROV AND C_O.DIR = C_L.DES_DIR) WHERE C_L.ID_DNI IS NOT NULL)  
    UNION
    (SELECT C_O.* FROM DIM_CLIENTE C_L
    RIGHT OUTER JOIN (SELECT 
    C.DNI,
    C.CUENTA,
    C.NOMBRE,
    C.APELLIDO1,
    C.APELLIDO2,
    D.ID_PROV,
    C.DIR,
    SYSTIMESTAMP
    FROM CLIENTE C LEFT OUTER JOIN DIM_PROV D ON C.CIUDAD = UPPER(D.DES_NOM_PROV)) C_O 
    ON (C_O.DNI = C_L.ID_DNI) WHERE C_L.ID_DNI IS NULL
    )
    UNION
    (SELECT C_O.* FROM DIM_CLIENTE C_L
    JOIN (SELECT 
    C.DNI,
    C.CUENTA,
    C.NOMBRE,
    C.APELLIDO1,
    C.APELLIDO2,
    D.ID_PROV,
    C.DIR,
    SYSTIMESTAMP
    FROM CLIENTE C LEFT OUTER JOIN DIM_PROV D ON C.CIUDAD = UPPER(D.DES_NOM_PROV)) C_O
    ON (C_O.DNI = C_L.ID_DNI) WHERE (C_O.CUENTA != C_L.COD_CUENTA OR C_O.NOMBRE != C_L.DES_NOMBRE 
      OR C_O.APELLIDO1 != C_L.DES_APE1 OR C_O.APELLIDO2 != C_L.DES_APE2 OR C_O.ID_PROV != C_L.ID_PROV OR C_O.DIR != C_L.DES_DIR)
    )
)';
EXECUTE IMMEDIATE CREA_TABLA_TEMP;
EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_CLIENTE';
EXECUTE IMMEDIATE 'INSERT INTO DIM_CLIENTE SELECT * FROM TEMP_CLIENTE';
COMMIT;
END;
