INSERT INTO ODI_DEMO.DIM_FECHA  SELECT 
#FECHA_INICIO + #I AS ID_FECHA, 
TO_CHAR (EXTRACT(DAY FROM #FECHA_INICIO + #I)) || ' DE ' || TO_CHAR (#FECHA_INICIO + #I, 'MONTH') || ' DE ' || TO_CHAR (EXTRACT(YEAR FROM #FECHA_INICIO + #I)) AS DES_FECHA, 
EXTRACT (DAY FROM #FECHA_INICIO + #I) AS ID_DIA,
EXTRACT (MONTH FROM #FECHA_INICIO + #I) AS ID_MES,
TO_CHAR (#FECHA_INICIO + #I, 'MONTH') AS DES_MES,
EXTRACT (YEAR FROM #FECHA_INICIO + #I) AS ID_ANO, 
TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM #FECHA_INICIO + #I)) || TO_CHAR(EXTRACT(MONTH FROM #FECHA_INICIO + #I))) AS ID_ANO_MES, 
TO_CHAR(EXTRACT(YEAR FROM #FECHA_INICIO + #I)) || TO_CHAR (#FECHA_INICIO + #I, 'MONTH') AS DES_ANO_MES,
LAST_DAY(#FECHA_INICIO + #I) AS FEC_ULTIM_D_MES, 
TRUNC(#FECHA_INICIO + #I, 'MM') AS FEC_PRIM_D_MES,
CASE
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (1,2,3) THEN 1
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (4,5,6) THEN 2
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (7,8,9) THEN 3
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (10,11,12) THEN 4  
END ID_TRIMESTRE,
CASE
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (1,2,3) THEN 'PRIMER TRIMESTRE' 
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (4,5,6) THEN 'SEGUNDO TRIMESTRE'
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (7,8,9) THEN 'TERCER TRIMESTRE'
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (10,11,12) THEN 'CUARTO TRIMESTRE'
END DES_TRIMESTRE,
CASE
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (1,2,3,4) THEN 1
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (5,6,7,8) THEN 2
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (9,10,11,12) THEN 3

END ID_CUATRIMESTRE,
CASE
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (1,2,3,4) THEN 'PRIMER CUATRIMESTRE'
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (5,6,7,8) THEN 'SEGUNDO CUATRIMESTRE'
    WHEN EXTRACT(MONTH FROM #FECHA_INICIO + #I) IN (9,10,11,12) THEN 'TERCER CUATRIMESTRE'

END DES_CUATRIMESTRE,

ADD_MONTHS(#FECHA_INICIO + #I, -12) AS FEC_ANO_ANTERIOR,
SYSDATE
FROM DUAL;
