CREATE OR REPLACE PROCEDURE PA_CARGA_COMPLETA
AS 

EXECUTE1 VARCHAR2(1000);
EXECUTE2 VARCHAR2(1000);
EXECUTE3 VARCHAR2(1000);
EXECUTE4 VARCHAR2(1000);
EXECUTE5 VARCHAR2(1000);
BEGIN

EXECUTE1:='BEGIN PROC_CREADO_INICIAL; END;';
EXECUTE IMMEDIATE EXECUTE1;
EXECUTE2 := 'BEGIN CARGA_DIM_FECHA; END;';
EXECUTE IMMEDIATE EXECUTE2;
EXECUTE4 := 'BEGIN CARGA_DIM_PROV; END;';
EXECUTE IMMEDIATE EXECUTE4;
EXECUTE3:='BEGIN CARGA_DIM_CLIENTE; END;';
EXECUTE IMMEDIATE EXECUTE3;
EXECUTE5 := 'BEGIN CARGA_HEC_TRANSAC; END;';
EXECUTE IMMEDIATE EXECUTE5;

END;
