CREATE OR REPLACE PROCEDURE PA_CARGA_INCREMENTAL
AS
EXECUTE1 VARCHAR2(1000);
EXECUTE2 VARCHAR2(1000);
BEGIN
EXECUTE1:='BEGIN CARGA_INCREMENTAL_CLIENTE; END;';
EXECUTE IMMEDIATE EXECUTE1;
EXECUTE2 := 'BEGIN CARGA_INCREMENTAL_HECHOS; END;';
EXECUTE IMMEDIATE EXECUTE2;

END; 
/

EXECUTE PA_CARGA_INCREMENTAL;
