select * from transacciones;
insert into transacciones values (TO_DATE('11/11/2022','DD/MM/YYYY'),  111111,    888888,    6000.00,    20.00,   'PRUEBA');
select * from transacciones;

CREATE OR REPLACE PROCEDURE CARGA_INCREMENTAL_HECHOS (fecha_input IN DATE)
AS
BEGIN 

DELETE FROM HEC_TRANSAC WHERE last_day(ID_FECHA) = last_day(fecha_input);

INSERT INTO HEC_TRANSAC       
SELECT 
TO_DATE(TO_CHAR(FECHAS.ID_FECHA,'DD/MM/YYYY')) AS ID_FECHA, --Valor por default aquí?
COALESCE(CLI_ORI.ID_DNI, -1) AS ID_DNI_CLI_ORIGEN, 
COALESCE(CLI_DES.ID_DNI, -1) AS ID_DNI_CLI_DESTINO,-- EL COALESCE ES PARA ESTABLECER EL VALOR POR DEFECTO DE -1, EN LUGAR DE METERLO EN LA CREACIÓN DE LAS TABLAS.
-- AQUÍ IRÍA ID_PROV PERO NO LO INCLUIMOS POR NO SER UN HECHO (SERIA O BIEN EL ID_PORV_CLI_ORIGEN O EL ID_PROV_CLI_DESTINO)
COALESCE(CLI_ORI.ID_PROV,-1) AS ID_PROV_CLI_ORIGEN,
COALESCE(CLI_DES.ID_PROV,-1) AS ID_PROV_CLI_DESTINO,
COALESCE(ORIGEN.IMPORTE,-1) AS IMP_IMPORTE, 
COALESCE(ORIGEN.COMISION,-1) AS IMP_COMISION,
COALESCE(ORIGEN.IMPORTE + ORIGEN.COMISION,ORIGEN.IMPORTE) AS IMP_TOTAL,
SYSTIMESTAMP AS FEC_AUDIT
FROM TRANSACCIONES ORIGEN 
LEFT OUTER JOIN DIM_FECHA FECHAS
ON TO_CHAR(ORIGEN.FECHA,'DD/MM/YYYY')=FECHAS.ID_FECHA
LEFT OUTER JOIN DIM_CLIENTE CLI_ORI
ON ORIGEN.CTA_ORIGEN = CLI_ORI.COD_CUENTA
LEFT OUTER JOIN DIM_CLIENTE CLI_DES
ON ORIGEN.CTA_DESTINO = CLI_DES.COD_CUENTA
WHERE last_day(TO_DATE(TO_CHAR(ID_FECHA,'DD/MM/YYYY'))) = last_day(TO_DATE(TO_CHAR(FECHA_INPUT,'DD/MM/YYYY')));

END;
/

EXECUTE carga_incremental_hechos(sysdate);

select * from hec_transac
